### ISSUE TITLE
Explicit boost/math/special_functions.hpp required with Boost 1.76

### ISSUE THREAD

**Issue by StefanBruens** [EttusResearch/uhd#437]
https://github.com/EttusResearch/uhd/blob/0813efb9a116d73300f6690b223295cf10a2f723/host/lib/usrp/usrp2/usrp2_impl.cpp#L920

Instead of the boost functions, std::copysign and std::round can be used as a replacement.

**Comment by ZeroChaos-** [comment]
bump

**Comment by mbr0wn** [comment]
Fix is on the way!

**Comment by StefanBruens** [comment]
> Fix is on the way!

Fix is available in PR #439 for 6 weeks ...

**Comment by loqs** [comment]
@mbrown does the fix cover host/lib/usrp/cores/rx_dsp_core_3000.cpp and host/lib/usrp/cores/rx_frontend_core_3000.cpp in addition to host/lib/usrp/usrp2/usrp2_impl.cpp?

**Comment by mbr0wn** [comment]
> @mbr0wn does the fix cover host/lib/usrp/cores/rx_dsp_core_3000.cpp and host/lib/usrp/cores/rx_frontend_core_3000.cpp in addition to host/lib/usrp/usrp2/usrp2_impl.cpp?

Yes. Will go public this week.

**Comment by mbr0wn** [comment]
Fix is public.

**Comment by loqs** [comment]
> > @mbr0wn does the fix cover host/lib/usrp/cores/rx_dsp_core_3000.cpp and host/lib/usrp/cores/rx_frontend_core_3000.cpp in addition to host/lib/usrp/usrp2/usrp2_impl.cpp?
> 
> Yes. Will go public this week.

@mbr0wn Build is still failing rx_dsp_core_3000.cpp and rx_frontend_core_3000.cpp.  What is supposed to be importing boost::math::sign ?

**Comment by loqs** [comment]
Fixed by https://github.com/EttusResearch/uhd/files/6750118/patch-UHD-4.1_build_with_Boost_1.76.0.diff.txt https://github.com/EttusResearch/uhd/issues/450#issuecomment-872461864
Just leaves the left over headers.

**Comment by michaelld** [comment]
@loqs can you explain "Just leaves the left over headers"?
